name: Build rootfs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: sudo apt install debootstrap sha256sum
      - run: sudo ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: rootfs
          path: |
            rootfs.tar
            rootfs.tar.sha256
